/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 10;
  int BOOLEAN = 11;
  int BREAK = 12;
  int CASE = 13;
  int CATCH = 14;
  int CHAR = 15;
  int CLASS = 16;
  int CONTINUE = 17;
  int DEF = 18;
  int DO = 19;
  int DOUBLE = 20;
  int ELSE = 21;
  int EXTENDS = 22;
  int FALSE = 23;
  int FINAL = 24;
  int FINALLY = 25;
  int FOR = 26;
  int IF = 27;
  int IMPLEMENTS = 28;
  int IMPORT = 29;
  int INSTANCEOF = 30;
  int INTERFACE = 31;
  int INT = 32;
  int LONG = 33;
  int NEW = 34;
  int NULL = 35;
  int PACKAGE = 36;
  int PRIVATE = 37;
  int PROTECTED = 38;
  int PUBLIC = 39;
  int RETURN = 40;
  int STATIC = 41;
  int SUPER = 42;
  int SWITCH = 43;
  int THIS = 44;
  int TRHOW = 45;
  int THROWS = 46;
  int TRUE = 47;
  int TRY = 48;
  int VOID = 49;
  int WHILE = 50;
  int PLUS = 51;
  int ASSIGN = 52;
  int DEC = 53;
  int EQUAL = 54;
  int GT = 55;
  int INC = 56;
  int LAND = 57;
  int LE = 58;
  int LNOT = 59;
  int MINUS = 60;
  int PLUS_ASSIGN = 61;
  int STAR = 62;
  int SEL = 63;
  int UCOMPLE = 64;
  int NEQUAL = 65;
  int DIV = 66;
  int DIV_ASSIGN = 67;
  int DEC_ASSIGN = 68;
  int STAR_ASSIGN = 69;
  int MODE = 70;
  int MODE_ASSIGN = 71;
  int ARS = 72;
  int RSHIFT_ASSIGN = 73;
  int LRS = 74;
  int LLSHIFT_ASSIGN = 75;
  int GTE = 76;
  int ALS = 77;
  int LSHIFT_ASSIGN = 78;
  int LS = 79;
  int XOR = 80;
  int XOR_ASSIGN = 81;
  int OR = 82;
  int OR_ASSIGN = 83;
  int LOR = 84;
  int AND = 85;
  int AND_ASSIGN = 86;
  int LPAREN = 87;
  int RPAREN = 88;
  int LCURLY = 89;
  int RCURLY = 90;
  int LBRACK = 91;
  int RBRACK = 92;
  int SEMI = 93;
  int COMMA = 94;
  int DOT = 95;
  int COL = 96;
  int IDENTIFIER = 97;
  int LETTER = 98;
  int DIGIT = 99;
  int NON_ZERO_DIGIT = 100;
  int INT_LITERAL = 101;
  int CHAR_LITERAL = 102;
  int LONG_LITERAL = 103;
  int EXPONENT = 104;
  int SUFFIX = 105;
  int DOUBLE_LITERAL = 106;
  int STRING_LITERAL = 107;
  int ESC = 108;
  int ERROR = 109;

  int DEFAULT = 0;
  int MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"for\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"interface\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"?\"",
    "\"~\"",
    "\"!=\"",
    "\"/\"",
    "\"/=\"",
    "\"-=\"",
    "\"*=\"",
    "\"%\"",
    "\"%=\"",
    "\">>\"",
    "\">>=\"",
    "\">>>\"",
    "\">>>=\"",
    "\">=\"",
    "\"<<\"",
    "\"<<=\"",
    "\"<\"",
    "\"^\"",
    "\"^=\"",
    "\"|\"",
    "\"|=\"",
    "\"||\"",
    "\"&\"",
    "\"&=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<LONG_LITERAL>",
    "<EXPONENT>",
    "<SUFFIX>",
    "<DOUBLE_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
